# This workflow will do clean build of the docker image

name: Docker Image CI (also tests build)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build the image
        run: |
          docker buildx build \
          --file Dockerfile \
          --tag rofl256/whiteboard:$(date +%s) \
          --platform linux/amd64,linux/arm64 .
